[package]
name    = "engine-core"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
glam      = { workspace = true }
hecs      = { workspace = true }
serde     = { workspace = true }
ron       = { workspace = true }
log       = { workspace = true }
smallvec  = { workspace = true }
