[package]
name    = "engine-physics"
version = "0.1.0"
edition = "2021"

[dependencies]
engine-core = { path = "../engine-core" }
engine-app  = { path = "../engine-app", default-features = false }
glam        = { workspace = true }
hecs        = { workspace = true }
log         = { workspace = true }

# parry3d used directly in narrowphase.rs for Aabb collision queries
parry3d = { version = "0.26", features = ["dim3", "f32"] }