[package]
name    = "engine-net"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
tokio    = { workspace = true }
quinn    = { workspace = true }
rustls   = { workspace = true }
rcgen    = { workspace = true }
postcard = { workspace = true }
serde    = { workspace = true }
log      = { workspace = true }
bytes    = { workspace = true }
